services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-spa
    ports:
      - "3001:5175"
    volumes:
      - ./src:/app   # mount source code để dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
